proxy:
  image: nginx:stable
  ports:
    - "8000:80"
  volumes:
    - ./:/code
    - ./docker/proxy/default.conf:/etc/nginx/conf.d/default.conf
  links:
    - app
app:
  build: ./docker/app
  volumes:
    - ./:/code
    - ./docker/app/90_php.ini:/usr/local/etc/php/conf.d/90_php.ini
  links:
    - database
  user: "1001"

database:
  image: mysql:5
  environment:
    - MYSQL_ROOT_PASSWORD="bienvenue"
  ports:
    - "3306"
